server:
  port: 8082
spring:
  application:
    name: movie-info-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/ddia_lab2_movieInfo

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

api:
  key: b0af84324ea41ca39f4311c9156e94e3