server:
  port: 8083
spring:
  application:
    name: ratings-data-service
  datasource:
    url: jdbc:mysql://localhost:3306/ddia_lab2_ratings
    username: root
    password: marwan1234#
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/