spring:
  application:
    name: trending-movie-service

grpc:
  server:
    port: 8084

eureka:
  instance:
    hostname: trending-movie-service
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/